FROM python:3.12-slim

WORKDIR /service
ENV STANZA_RESOURCES_DIR=/models
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY app.py .
EXPOSE 8008
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8008"]
