'use client';

import { FormEvent, useEffect, useState } from 'react';
import { CalendarEvent, Manuscript } from '@eldritch/domain';
import { db } from '../../db/schema';
import { useApp } from '../../context/AppContext';
import './calendar.css';

const categories: CalendarEvent['category'][] = ['DEADLINE', 'MEETING', 'SPRINT', 'VACATION'];
export default function CalendarPage() {
  const { activeProject } = useApp(); const [events, setEvents] = useState<CalendarEvent[]>([]); const [chapters, setChapters] = useState<Manuscript[]>([]); const [creating, setCreating] = useState(false); const [title, setTitle] = useState(''); const [date, setDate] = useState(''); const [category, setCategory] = useState<CalendarEvent['category']>('DEADLINE'); const [chapterId, setChapterId] = useState('');
  const load = async () => { if (!activeProject) return; const [stored, manuscripts] = await Promise.all([db.calendarEvents.where('projectId').equals(activeProject.id).toArray(), db.manuscripts.toArray()]); setEvents(stored.sort((a,b) => a.startDate.localeCompare(b.startDate))); setChapters(manuscripts.filter(manuscript => manuscript.projectId === activeProject.id && !manuscript.inTrash)); };
  useEffect(() => { void load(); }, [activeProject?.id]);
  const add = async (event: FormEvent) => { event.preventDefault(); if (!activeProject || !title.trim() || !date) return; const chapter = chapters.find(item => item.id === chapterId); await db.calendarEvents.put({ id: crypto.randomUUID(), projectId: activeProject.id, title: title.trim(), startDate: date, timezone: Intl.DateTimeFormat().resolvedOptions().timeZone, category, colorTag: category === 'DEADLINE' ? '#d93025' : category === 'MEETING' ? '#1a73e8' : '#188038', assigneeEmails: [], description: chapter ? `Capítulo relacionado: ${chapter.title}` : undefined, createdAt: new Date().toISOString() }); setTitle('');setDate('');setChapterId('');setCreating(false);await load(); };
  const remove = async (id:string) => { await db.calendarEvents.delete(id); await load(); };
  return <main className="page calendar-page"><header className="page-heading"><div><p className="eyebrow">Colaboração</p><h1>Calendário do projeto</h1><p>Prazos e encontros ligados ao trabalho que está acontecendo no manuscrito.</p></div><button className="primary-button" onClick={() => setCreating(true)}>Novo evento</button></header>{creating && <form className="surface-card calendar-form" onSubmit={add}><label>Título<input value={title} onChange={event=>setTitle(event.target.value)} autoFocus placeholder="Revisar capítulo" /></label><label>Data<input type="date" value={date} onChange={event=>setDate(event.target.value)} /></label><label>Tipo<select value={category} onChange={event=>setCategory(event.target.value as CalendarEvent['category'])}>{categories.map(item=><option key={item}>{item}</option>)}</select></label><label>Capítulo relacionado<select value={chapterId} onChange={event=>setChapterId(event.target.value)}><option value="">Nenhum</option>{chapters.map(chapter=><option key={chapter.id} value={chapter.id}>{chapter.title}</option>)}</select></label><div><button type="button" className="secondary-button" onClick={()=>setCreating(false)}>Cancelar</button><button className="primary-button">Agendar</button></div></form>}<section className="calendar-list">{events.map(item=><article className="surface-card calendar-event" key={item.id}><time>{new Date(`${item.startDate}T12:00:00`).toLocaleDateString('pt-BR',{day:'2-digit',month:'short',year:'numeric'})}</time><div><span>{item.category.toLowerCase()}</span><h2>{item.title}</h2>{item.description&&<p>{item.description}</p>}</div><button type="button" onClick={()=>void remove(item.id)}>Remover</button></article>)}{!events.length&&<div className="empty-state"><h2>Nenhum evento agendado.</h2><p>Crie um prazo para um capítulo, uma revisão ou uma reunião.</p></div>}</section></main>;
}
