'use client';

import { FormEvent, MouseEvent, useEffect, useRef, useState } from 'react';
import { GeoMap, GeoMapMarker } from '@eldritch/domain';
import { db, WikiEntity } from '../../db/schema';
import { useApp } from '../../context/AppContext';
import './maps.css';

export default function MapsPage() {
  const { activeProject }=useApp();const[maps,setMaps]=useState<GeoMap[]>([]);const[markers,setMarkers]=useState<GeoMapMarker[]>([]);const[locations,setLocations]=useState<WikiEntity[]>([]);const[mapId,setMapId]=useState('');const[creating,setCreating]=useState(false);const[name,setName]=useState('');const[markerName,setMarkerName]=useState('');const[entityId,setEntityId]=useState('');const[x,setX]=useState(50);const[y,setY]=useState(50);const mapCanvasRef=useRef<HTMLDivElement>(null);
  const active=maps.find(map=>map.id===mapId)??null;
  const load=async()=>{if(!activeProject)return;const[storedMaps,entities]=await Promise.all([db.geoMaps.where('projectId').equals(activeProject.id).toArray(),db.wikiEntities.where('projectId').equals(activeProject.id).toArray()]);setMaps(storedMaps);setLocations(entities.filter(entity=>entity.type==='Local'));setMapId(current=>storedMaps.some(map=>map.id===current)?current:storedMaps[0]?.id??'');};
  const loadMarkers=async()=>{setMarkers(mapId?await db.geoMapMarkers.where('mapId').equals(mapId).toArray():[]);};useEffect(()=>{void load();},[activeProject?.id]);useEffect(()=>{void loadMarkers();},[mapId]);
  const addMap=async(event:FormEvent)=>{event.preventDefault();if(!activeProject||!name.trim())return;const now=new Date().toISOString();const map={id:crypto.randomUUID(),projectId:activeProject.id,name:name.trim(),createdAt:now,updatedAt:now};await db.geoMaps.put(map);setName('');setCreating(false);await load();setMapId(map.id);};
  const addMarker=async(event:FormEvent)=>{event.preventDefault();if(!active||!markerName.trim())return;await db.geoMapMarkers.put({id:crypto.randomUUID(),mapId:active.id,entityId:entityId||undefined,name:markerName.trim(),type:'location',xPercent:x,yPercent:y});setMarkerName('');setEntityId('');await loadMarkers();};
  const markFromClick=async(event:MouseEvent<HTMLDivElement>)=>{if(!active)return;if(!markerName.trim()){alert('Escolha ou escreva o nome do marcador antes de clicar no mapa.');return;}const rect=event.currentTarget.getBoundingClientRect();const nextX=Math.round((event.clientX-rect.left)/rect.width*100);const nextY=Math.round((event.clientY-rect.top)/rect.height*100);setX(nextX);setY(nextY);await db.geoMapMarkers.put({id:crypto.randomUUID(),mapId:active.id,entityId:entityId||undefined,name:markerName.trim(),type:'location',xPercent:nextX,yPercent:nextY});setMarkerName('');setEntityId('');await loadMarkers();};
  const exportImage=()=>{if(!active)return;const canvas=document.createElement('canvas');canvas.width=1400;canvas.height=900;const ctx=canvas.getContext('2d');if(!ctx)return;ctx.fillStyle='#f8fbff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle='#e8f0fe';for(let n=0;n<canvas.width;n+=48){ctx.beginPath();ctx.moveTo(n,0);ctx.lineTo(n,canvas.height);ctx.stroke();}for(let n=0;n<canvas.height;n+=48){ctx.beginPath();ctx.moveTo(0,n);ctx.lineTo(canvas.width,n);ctx.stroke();}ctx.fillStyle='#202124';ctx.font='bold 28px Arial';ctx.fillText(active.name,36,48);markers.forEach(marker=>{const px=marker.xPercent/100*canvas.width,py=marker.yPercent/100*canvas.height;ctx.fillStyle='#1a73e8';ctx.beginPath();ctx.arc(px,py,10,0,Math.PI*2);ctx.fill();ctx.fillStyle='#174ea6';ctx.font='18px Arial';ctx.fillText(marker.name,px+16,py+6);});const link=document.createElement('a');link.href=canvas.toDataURL('image/png');link.download=`${active.name.toLowerCase().replace(/[^a-z0-9]+/gi,'-')||'atlas'}.png`;link.click();};
  return <main className="page maps-page"><header className="page-heading"><div><p className="eyebrow">Construção da história</p><h1>Atlas do universo</h1><p>Posicione os locais que já existem no seu mundo em mapas definidos por você.</p></div><div><button className="secondary-button" onClick={exportImage} disabled={!active}>Exportar PNG</button><button className="primary-button" onClick={()=>setCreating(true)}>Novo mapa</button></div></header>{creating&&<form className="surface-card map-create" onSubmit={addMap}><input autoFocus value={name} onChange={event=>setName(event.target.value)} placeholder="Nome do mapa"/><button className="primary-button">Criar mapa</button><button className="secondary-button" type="button" onClick={()=>setCreating(false)}>Cancelar</button></form>}<section className="map-switcher">{maps.map(map=><button key={map.id} className={map.id===mapId?'is-active':''} onClick={()=>setMapId(map.id)}>{map.name}</button>)}</section>{!active?<div className="empty-state"><h2>Crie o primeiro mapa.</h2><p>Depois, adicione os locais cadastrados no Universo.</p></div>:<section className="atlas-layout"><div className="surface-card atlas"><header><h2>{active.name}</h2><span>{markers.length} marcadores</span></header><div ref={mapCanvasRef} className="map-grid" onClick={event=>void markFromClick(event)}>{markers.map(marker=><div className="map-marker" style={{left:`${marker.xPercent}%`,top:`${marker.yPercent}%`}} key={marker.id} title={marker.description}><i/> <span>{marker.name}</span></div>)}</div></div><form className="surface-card marker-form" onSubmit={addMarker}><h2>Adicionar local</h2><p>Clique no mapa para posicionar o nome informado.</p><label>Local cadastrado<select value={entityId} onChange={event=>{setEntityId(event.target.value);setMarkerName(locations.find(item=>item.id===event.target.value)?.name??markerName);}}><option value="">Marcador livre</option>{locations.map(location=><option key={location.id} value={location.id}>{location.name}</option>)}</select></label><label>Nome<input value={markerName} onChange={event=>setMarkerName(event.target.value)} required/></label><label>X: {x}%<input type="range" min="0" max="100" value={x} onChange={event=>setX(Number(event.target.value))}/></label><label>Y: {y}%<input type="range" min="0" max="100" value={y} onChange={event=>setY(Number(event.target.value))}/></label><button className="primary-button">Posicionar pelos controles</button></form></section>}</main>;
}
