import Dexie, { Table } from 'dexie';
import { MetaNode, MetaEdge, WritingGoal, WritingLog, WritingStreak, Manuscript, Folder, InlineComment, SystemActivity } from '@eldritch/domain';

export interface Reminder {
  id: string;
  text: string;
  projectId: string;
  manuscriptId?: string;
  alertTime: string;
  importance: 'LOW' | 'MEDIUM' | 'HIGH';
  isRead: boolean;
  createdAt: string;
}

export interface WikiEntity {
  id: string;
  projectId: string;
  name: string;
  type: 'Personagem' | 'Local' | 'Item' | 'Organizacao';
  description: string;
  content: string;
  isConfidential: boolean;
  createdAt: string;
  updatedAt: string;
}

export class EldritchDatabase extends Dexie {
  metaNodes!: Table<MetaNode, string>;
  metaEdges!: Table<MetaEdge, string>;
  writingGoals!: Table<WritingGoal, string>;
  writingLogs!: Table<WritingLog, string>;
  writingStreak!: Table<WritingStreak, string>;
  keyboardShortcuts!: Table<{ command: string; keyCombo: string }, string>;
  manuscripts!: Table<Manuscript, string>;
  manuscriptVersions!: Table<{ id: string; manuscriptId: string; versionNumber: number; title: string; content: string; createdAt: string }, string>;
  pendingSaves!: Table<{ id: string; manuscriptId: string; content: string; timestamp: number }, string>;
  folders!: Table<Folder, string>;
  comments!: Table<InlineComment, string>;
  auditLogs!: Table<SystemActivity, string>;
  reminders!: Table<Reminder, string>;
  wikiEntities!: Table<WikiEntity, string>;
  timelines!: Table<import('@eldritch/domain').Timeline, string>;
  timelineEvents!: Table<import('@eldritch/domain').TimelineEvent, string>;
  geoMaps!: Table<import('@eldritch/domain').GeoMap, string>;
  geoMapMarkers!: Table<import('@eldritch/domain').GeoMapMarker, string>;
  mindMaps!: Table<import('@eldritch/domain').MindMap, string>;
  mindMapNodes!: Table<import('@eldritch/domain').MindMapNode, string>;
  mediaAssets!: Table<import('@eldritch/domain').MediaAsset, string>;
  storyActs!: Table<import('@eldritch/domain').StoryAct, string>;
  heroJourneyStages!: Table<import('@eldritch/domain').HeroJourneyStage, string>;
  characterArcPoints!: Table<import('@eldritch/domain').CharacterArcPoint, string>;
  sandboxes!: Table<import('@eldritch/domain').SandboxEnvironment, string>;
  sandboxChanges!: Table<import('@eldritch/domain').SandboxChange, string>;
  projectMembers!: Table<import('@eldritch/domain').ProjectMember, string>;
  sharedDocLinks!: Table<import('@eldritch/domain').SharedDocumentLink, string>;
  projectInviteLinks!: Table<import('@eldritch/domain').ProjectInviteLink, string>;
  collaborationAuditLogs!: Table<import('@eldritch/domain').CollaborationAuditLog, string>;
  chatChannels!: Table<import('@eldritch/domain').ChatChannel, string>;
  chatMessages!: Table<import('@eldritch/domain').ChatMessage, string>;
  notificationSettings!: Table<import('@eldritch/domain').NotificationSettings, string>;
  teamMeetings!: Table<import('@eldritch/domain').TeamMeeting, string>;
  voiceMessages!: Table<import('@eldritch/domain').VoiceMessage, string>;
  callSessions!: Table<import('@eldritch/domain').CallSession, string>;
  calendarEvents!: Table<import('@eldritch/domain').CalendarEvent, string>;
  memberAvailabilities!: Table<import('@eldritch/domain').MemberAvailability, string>;
  employees!: Table<import('@eldritch/domain').Employee, string>;
  payrollRecords!: Table<import('@eldritch/domain').PayrollRecord, string>;
  vacationRequests!: Table<import('@eldritch/domain').VacationRequest, string>;
  timeClockPunches!: Table<import('@eldritch/domain').TimeClockPunch, string>;
  referenceItems!: Table<import('@eldritch/domain').ReferenceItem, string>;
  researchNotes!: Table<import('@eldritch/domain').ResearchNote, string>;
  gameMechanics!: Table<import('@eldritch/domain').GameMechanic, string>;
  playableCharacterBalances!: Table<import('@eldritch/domain').PlayableCharacterBalance, string>;
  gameRules!: Table<import('@eldritch/domain').GameRule, string>;
  gameLevels!: Table<import('@eldritch/domain').GameLevel, string>;
  gameShops!: Table<import('@eldritch/domain').GameShop, string>;
  objectiveOkrs!: Table<import('@eldritch/domain').ObjectiveOkr, string>;
  okrCheckInLogs!: Table<import('@eldritch/domain').OkrCheckInLog, string>;
  okrTaskLinks!: Table<import('@eldritch/domain').OkrTaskLink, string>;
  corporatePortfolios!: Table<import('@eldritch/domain').CorporatePortfolio, string>;
  resourceAllocations!: Table<import('@eldritch/domain').ResourceAllocation, string>;
  projectCostLogs!: Table<import('@eldritch/domain').ProjectCostLog, string>;
  projectFinancials!: Table<import('@eldritch/domain').ProjectFinancials, string>;

  constructor() {
    const isBrowser = typeof window !== 'undefined';
    const activeProjectId = isBrowser ? localStorage.getItem('activeProjectId') || 'default' : 'default';
    super(`EldritchDatabase_${activeProjectId}`);
    this.version(1).stores({
      metaNodes: 'id, type, status, title',
      metaEdges: 'id, fromId, toId'
    });
    this.version(2).stores({
      metaNodes: 'id, type, status, title',
      metaEdges: 'id, fromId, toId',
      writingGoals: 'id, type, targetWords, deadline',
      writingLogs: 'id, date',
      writingStreak: 'id'
    });
    this.version(3).stores({
      metaNodes: 'id, type, status, title',
      metaEdges: 'id, fromId, toId',
      writingGoals: 'id, type, targetWords, deadline',
      writingLogs: 'id, date',
      writingStreak: 'id',
      keyboardShortcuts: 'command'
    });
    this.version(4).stores({
      metaNodes: 'id, type, status, title',
      metaEdges: 'id, fromId, toId',
      writingGoals: 'id, type, targetWords, deadline',
      writingLogs: 'id, date',
      writingStreak: 'id',
      keyboardShortcuts: 'command',
      manuscripts: 'id, status, title'
    });
    this.version(5).stores({
      metaNodes: 'id, type, status, title',
      metaEdges: 'id, fromId, toId',
      writingGoals: 'id, type, targetWords, deadline',
      writingLogs: 'id, date',
      writingStreak: 'id',
      keyboardShortcuts: 'command',
      manuscripts: 'id, status, title',
      manuscriptVersions: 'id, manuscriptId, versionNumber, createdAt',
      pendingSaves: 'id, manuscriptId, timestamp'
    });
    this.version(6).stores({
      metaNodes: 'id, type, status, title',
      metaEdges: 'id, fromId, toId',
      writingGoals: 'id, type, targetWords, deadline',
      writingLogs: 'id, date',
      writingStreak: 'id',
      keyboardShortcuts: 'command',
      manuscripts: 'id, status, title, folderId',
      manuscriptVersions: 'id, manuscriptId, versionNumber, createdAt',
      pendingSaves: 'id, manuscriptId, timestamp',
      folders: 'id, projectId, parentFolderId'
    });
    this.version(7).stores({
      metaNodes: 'id, type, status, title',
      metaEdges: 'id, fromId, toId',
      writingGoals: 'id, type, targetWords, deadline',
      writingLogs: 'id, date',
      writingStreak: 'id',
      keyboardShortcuts: 'command',
      manuscripts: 'id, status, title, folderId',
      manuscriptVersions: 'id, manuscriptId, versionNumber, createdAt',
      pendingSaves: 'id, manuscriptId, timestamp',
      folders: 'id, projectId, parentFolderId',
      comments: 'id, manuscriptId, isResolved, createdAt'
    });
    this.version(8).stores({
      metaNodes: 'id, type, status, title',
      metaEdges: 'id, fromId, toId',
      writingGoals: 'id, type, targetWords, deadline',
      writingLogs: 'id, date',
      writingStreak: 'id',
      keyboardShortcuts: 'command',
      manuscripts: 'id, status, title, folderId',
      manuscriptVersions: 'id, manuscriptId, versionNumber, createdAt',
      pendingSaves: 'id, manuscriptId, timestamp',
      folders: 'id, projectId, parentFolderId',
      comments: 'id, manuscriptId, isResolved, createdAt',
      auditLogs: 'id, type, timestamp'
    });
    this.version(9).stores({
      metaNodes: 'id, type, status, title',
      metaEdges: 'id, fromId, toId',
      writingGoals: 'id, type, targetWords, deadline',
      writingLogs: 'id, date',
      writingStreak: 'id',
      keyboardShortcuts: 'command',
      manuscripts: 'id, status, title, folderId, category, isArchived',
      manuscriptVersions: 'id, manuscriptId, versionNumber, createdAt',
      pendingSaves: 'id, manuscriptId, timestamp',
      folders: 'id, projectId, parentFolderId',
      comments: 'id, manuscriptId, isResolved, createdAt',
      auditLogs: 'id, type, timestamp'
    });
    this.version(10).stores({
      metaNodes: 'id, type, status, title',
      metaEdges: 'id, fromId, toId',
      writingGoals: 'id, type, targetWords, deadline',
      writingLogs: 'id, date',
      writingStreak: 'id',
      keyboardShortcuts: 'command',
      manuscripts: 'id, status, title, folderId, category, isArchived',
      manuscriptVersions: 'id, manuscriptId, versionNumber, createdAt',
      pendingSaves: 'id, manuscriptId, timestamp',
      folders: 'id, projectId, parentFolderId',
      comments: 'id, manuscriptId, isResolved, createdAt',
      auditLogs: 'id, type, timestamp',
      reminders: 'id, projectId, alertTime, isRead'
    });
    this.version(11).stores({
      metaNodes: 'id, type, status, title',
      metaEdges: 'id, fromId, toId',
      writingGoals: 'id, type, targetWords, deadline',
      writingLogs: 'id, date',
      writingStreak: 'id',
      keyboardShortcuts: 'command',
      manuscripts: 'id, status, title, folderId, category, isArchived',
      manuscriptVersions: 'id, manuscriptId, versionNumber, createdAt',
      pendingSaves: 'id, manuscriptId, timestamp',
      folders: 'id, projectId, parentFolderId',
      comments: 'id, manuscriptId, isResolved, createdAt',
      auditLogs: 'id, type, timestamp',
      reminders: 'id, projectId, alertTime, isRead',
      wikiEntities: 'id, projectId, name, type, isConfidential'
    });
    this.version(12).stores({
      metaNodes: 'id, type, status, title',
      metaEdges: 'id, fromId, toId',
      writingGoals: 'id, type, targetWords, deadline',
      writingLogs: 'id, date',
      writingStreak: 'id',
      keyboardShortcuts: 'command',
      manuscripts: 'id, status, title, folderId, category, isArchived',
      manuscriptVersions: 'id, manuscriptId, versionNumber, createdAt',
      pendingSaves: 'id, manuscriptId, timestamp',
      folders: 'id, projectId, parentFolderId',
      comments: 'id, manuscriptId, isResolved, createdAt',
      auditLogs: 'id, type, timestamp',
      reminders: 'id, projectId, alertTime, isRead',
      wikiEntities: 'id, projectId, name, type, isConfidential',
      timelines: 'id, projectId, name',
      timelineEvents: 'id, timelineId, sortOrder'
    });
    this.version(13).stores({
      metaNodes: 'id, type, status, title',
      metaEdges: 'id, fromId, toId',
      writingGoals: 'id, type, targetWords, deadline',
      writingLogs: 'id, date',
      writingStreak: 'id',
      keyboardShortcuts: 'command',
      manuscripts: 'id, status, title, folderId, category, isArchived',
      manuscriptVersions: 'id, manuscriptId, versionNumber, createdAt',
      pendingSaves: 'id, manuscriptId, timestamp',
      folders: 'id, projectId, parentFolderId',
      comments: 'id, manuscriptId, isResolved, createdAt',
      auditLogs: 'id, type, timestamp',
      reminders: 'id, projectId, alertTime, isRead',
      wikiEntities: 'id, projectId, name, type, isConfidential',
      timelines: 'id, projectId, name',
      timelineEvents: 'id, timelineId, sortOrder',
      geoMaps: 'id, projectId, name',
      geoMapMarkers: 'id, mapId, type'
    });
    this.version(14).stores({
      metaNodes: 'id, type, status, title',
      metaEdges: 'id, fromId, toId',
      writingGoals: 'id, type, targetWords, deadline',
      writingLogs: 'id, date',
      writingStreak: 'id',
      keyboardShortcuts: 'command',
      manuscripts: 'id, status, title, folderId, category, isArchived',
      manuscriptVersions: 'id, manuscriptId, versionNumber, createdAt',
      pendingSaves: 'id, manuscriptId, timestamp',
      folders: 'id, projectId, parentFolderId',
      comments: 'id, manuscriptId, isResolved, createdAt',
      auditLogs: 'id, type, timestamp',
      reminders: 'id, projectId, alertTime, isRead',
      wikiEntities: 'id, projectId, name, type, isConfidential',
      timelines: 'id, projectId, name',
      timelineEvents: 'id, timelineId, sortOrder',
      geoMaps: 'id, projectId, name',
      geoMapMarkers: 'id, mapId, type',
      mindMaps: 'id, projectId, title',
      mindMapNodes: 'id, mindMapId, parentId'
    });
    this.version(15).stores({
      metaNodes: 'id, type, status, title',
      metaEdges: 'id, fromId, toId',
      writingGoals: 'id, type, targetWords, deadline',
      writingLogs: 'id, date',
      writingStreak: 'id',
      keyboardShortcuts: 'command',
      manuscripts: 'id, status, title, folderId, category, isArchived',
      manuscriptVersions: 'id, manuscriptId, versionNumber, createdAt',
      pendingSaves: 'id, manuscriptId, timestamp',
      folders: 'id, projectId, parentFolderId',
      comments: 'id, manuscriptId, isResolved, createdAt',
      auditLogs: 'id, type, timestamp',
      reminders: 'id, projectId, alertTime, isRead',
      wikiEntities: 'id, projectId, name, type, isConfidential',
      timelines: 'id, projectId, name',
      timelineEvents: 'id, timelineId, sortOrder',
      geoMaps: 'id, projectId, name',
      geoMapMarkers: 'id, mapId, type',
      mindMaps: 'id, projectId, title',
      mindMapNodes: 'id, mindMapId, parentId',
      mediaAssets: 'id, projectId, category, entityName'
    });
    this.version(16).stores({
      metaNodes: 'id, type, status, title',
      metaEdges: 'id, fromId, toId',
      writingGoals: 'id, type, targetWords, deadline',
      writingLogs: 'id, date',
      writingStreak: 'id',
      keyboardShortcuts: 'command',
      manuscripts: 'id, status, title, folderId, category, isArchived',
      manuscriptVersions: 'id, manuscriptId, versionNumber, createdAt',
      pendingSaves: 'id, manuscriptId, timestamp',
      folders: 'id, projectId, parentFolderId',
      comments: 'id, manuscriptId, isResolved, createdAt',
      auditLogs: 'id, type, timestamp',
      reminders: 'id, projectId, alertTime, isRead',
      wikiEntities: 'id, projectId, name, type, isConfidential',
      timelines: 'id, projectId, name',
      timelineEvents: 'id, timelineId, sortOrder',
      geoMaps: 'id, projectId, name',
      geoMapMarkers: 'id, mapId, type',
      mindMaps: 'id, projectId, title',
      mindMapNodes: 'id, mindMapId, parentId',
      mediaAssets: 'id, projectId, category, entityName',
      storyActs: 'id, projectId, sortOrder',
      heroJourneyStages: 'id, projectId, characterName, stepNumber'
    });
    this.version(17).stores({
      metaNodes: 'id, type, status, title',
      metaEdges: 'id, fromId, toId',
      writingGoals: 'id, type, targetWords, deadline',
      writingLogs: 'id, date',
      writingStreak: 'id',
      keyboardShortcuts: 'command',
      manuscripts: 'id, status, title, folderId, category, isArchived',
      manuscriptVersions: 'id, manuscriptId, versionNumber, createdAt',
      pendingSaves: 'id, manuscriptId, timestamp',
      folders: 'id, projectId, parentFolderId',
      comments: 'id, manuscriptId, isResolved, createdAt',
      auditLogs: 'id, type, timestamp',
      reminders: 'id, projectId, alertTime, isRead',
      wikiEntities: 'id, projectId, name, type, isConfidential',
      timelines: 'id, projectId, name',
      timelineEvents: 'id, timelineId, sortOrder',
      geoMaps: 'id, projectId, name',
      geoMapMarkers: 'id, mapId, type',
      mindMaps: 'id, projectId, title',
      mindMapNodes: 'id, mindMapId, parentId',
      mediaAssets: 'id, projectId, category, entityName',
      storyActs: 'id, projectId, sortOrder',
      heroJourneyStages: 'id, projectId, characterName, stepNumber',
      characterArcPoints: 'id, projectId, characterName, sortOrder'
    });
    this.version(18).stores({
      metaNodes: 'id, type, status, title',
      metaEdges: 'id, fromId, toId',
      writingGoals: 'id, type, targetWords, deadline',
      writingLogs: 'id, date',
      writingStreak: 'id',
      keyboardShortcuts: 'command',
      manuscripts: 'id, status, title, folderId, category, isArchived',
      manuscriptVersions: 'id, manuscriptId, versionNumber, createdAt',
      pendingSaves: 'id, manuscriptId, timestamp',
      folders: 'id, projectId, parentFolderId',
      comments: 'id, manuscriptId, isResolved, createdAt',
      auditLogs: 'id, type, timestamp',
      reminders: 'id, projectId, alertTime, isRead',
      wikiEntities: 'id, projectId, name, type, isConfidential',
      timelines: 'id, projectId, name',
      timelineEvents: 'id, timelineId, sortOrder',
      geoMaps: 'id, projectId, name',
      geoMapMarkers: 'id, mapId, type',
      mindMaps: 'id, projectId, title',
      mindMapNodes: 'id, mindMapId, parentId',
      mediaAssets: 'id, projectId, category, entityName',
      storyActs: 'id, projectId, sortOrder',
      heroJourneyStages: 'id, projectId, characterName, stepNumber',
      characterArcPoints: 'id, projectId, characterName, sortOrder',
      sandboxes: 'id, projectId, name, isPromoted',
      sandboxChanges: 'id, sandboxId, entityType'
    });
    this.version(19).stores({
      metaNodes: 'id, type, status, title',
      metaEdges: 'id, fromId, toId',
      writingGoals: 'id, type, targetWords, deadline',
      writingLogs: 'id, date',
      writingStreak: 'id',
      keyboardShortcuts: 'command',
      manuscripts: 'id, status, title, folderId, category, isArchived',
      manuscriptVersions: 'id, manuscriptId, versionNumber, createdAt',
      pendingSaves: 'id, manuscriptId, timestamp',
      folders: 'id, projectId, parentFolderId',
      comments: 'id, manuscriptId, isResolved, createdAt',
      auditLogs: 'id, type, timestamp',
      reminders: 'id, projectId, alertTime, isRead',
      wikiEntities: 'id, projectId, name, type, isConfidential',
      timelines: 'id, projectId, name',
      timelineEvents: 'id, timelineId, sortOrder',
      geoMaps: 'id, projectId, name',
      geoMapMarkers: 'id, mapId, type',
      mindMaps: 'id, projectId, title',
      mindMapNodes: 'id, mindMapId, parentId',
      mediaAssets: 'id, projectId, category, entityName',
      storyActs: 'id, projectId, sortOrder',
      heroJourneyStages: 'id, projectId, characterName, stepNumber',
      characterArcPoints: 'id, projectId, characterName, sortOrder',
      sandboxes: 'id, projectId, name, isPromoted',
      sandboxChanges: 'id, sandboxId, entityType',
      projectMembers: 'id, projectId, userEmail, role',
      sharedDocLinks: 'id, manuscriptId, token',
      projectInviteLinks: 'id, projectId, token, isRevoked',
      collaborationAuditLogs: 'id, projectId, userId, timestamp'
    });
    this.version(20).stores({
      metaNodes: 'id, type, status, title',
      metaEdges: 'id, fromId, toId',
      writingGoals: 'id, type, targetWords, deadline',
      writingLogs: 'id, date',
      writingStreak: 'id',
      keyboardShortcuts: 'command',
      manuscripts: 'id, status, title, folderId, category, isArchived',
      manuscriptVersions: 'id, manuscriptId, versionNumber, createdAt',
      pendingSaves: 'id, manuscriptId, timestamp',
      folders: 'id, projectId, parentFolderId',
      comments: 'id, manuscriptId, isResolved, createdAt',
      auditLogs: 'id, type, timestamp',
      reminders: 'id, projectId, alertTime, isRead',
      wikiEntities: 'id, projectId, name, type, isConfidential',
      timelines: 'id, projectId, name',
      timelineEvents: 'id, timelineId, sortOrder',
      geoMaps: 'id, projectId, name',
      geoMapMarkers: 'id, mapId, type',
      mindMaps: 'id, projectId, title',
      mindMapNodes: 'id, mindMapId, parentId',
      mediaAssets: 'id, projectId, category, entityName',
      storyActs: 'id, projectId, sortOrder',
      heroJourneyStages: 'id, projectId, characterName, stepNumber',
      characterArcPoints: 'id, projectId, characterName, sortOrder',
      sandboxes: 'id, projectId, name, isPromoted',
      sandboxChanges: 'id, sandboxId, entityType',
      projectMembers: 'id, projectId, userEmail, role',
      sharedDocLinks: 'id, manuscriptId, token',
      projectInviteLinks: 'id, projectId, token, isRevoked',
      collaborationAuditLogs: 'id, projectId, userId, timestamp',
      chatChannels: 'id, projectId, isArchived',
      chatMessages: 'id, channelId, createdAt'
    });
    this.version(21).stores({
      metaNodes: 'id, type, status, title',
      metaEdges: 'id, fromId, toId',
      writingGoals: 'id, type, targetWords, deadline',
      writingLogs: 'id, date',
      writingStreak: 'id',
      keyboardShortcuts: 'command',
      manuscripts: 'id, status, title, folderId, category, isArchived',
      manuscriptVersions: 'id, manuscriptId, versionNumber, createdAt',
      pendingSaves: 'id, manuscriptId, timestamp',
      folders: 'id, projectId, parentFolderId',
      comments: 'id, manuscriptId, isResolved, createdAt',
      auditLogs: 'id, type, timestamp',
      reminders: 'id, projectId, alertTime, isRead',
      wikiEntities: 'id, projectId, name, type, isConfidential',
      timelines: 'id, projectId, name',
      timelineEvents: 'id, timelineId, sortOrder',
      geoMaps: 'id, projectId, name',
      geoMapMarkers: 'id, mapId, type',
      mindMaps: 'id, projectId, title',
      mindMapNodes: 'id, mindMapId, parentId',
      mediaAssets: 'id, projectId, category, entityName',
      storyActs: 'id, projectId, sortOrder',
      heroJourneyStages: 'id, projectId, characterName, stepNumber',
      characterArcPoints: 'id, projectId, characterName, sortOrder',
      sandboxes: 'id, projectId, name, isPromoted',
      sandboxChanges: 'id, sandboxId, entityType',
      projectMembers: 'id, projectId, userEmail, role',
      sharedDocLinks: 'id, manuscriptId, token',
      projectInviteLinks: 'id, projectId, token, isRevoked',
      collaborationAuditLogs: 'id, projectId, userId, timestamp',
      chatChannels: 'id, projectId, isArchived',
      chatMessages: 'id, channelId, createdAt',
      notificationSettings: 'id, userId, emailFrequency'
    });
    this.version(22).stores({
      metaNodes: 'id, type, status, title',
      metaEdges: 'id, fromId, toId',
      writingGoals: 'id, type, targetWords, deadline',
      writingLogs: 'id, date',
      writingStreak: 'id',
      keyboardShortcuts: 'command',
      manuscripts: 'id, status, title, folderId, category, isArchived',
      manuscriptVersions: 'id, manuscriptId, versionNumber, createdAt',
      pendingSaves: 'id, manuscriptId, timestamp',
      folders: 'id, projectId, parentFolderId',
      comments: 'id, manuscriptId, isResolved, createdAt',
      auditLogs: 'id, type, timestamp',
      reminders: 'id, projectId, alertTime, isRead',
      wikiEntities: 'id, projectId, name, type, isConfidential',
      timelines: 'id, projectId, name',
      timelineEvents: 'id, timelineId, sortOrder',
      geoMaps: 'id, projectId, name',
      geoMapMarkers: 'id, mapId, type',
      mindMaps: 'id, projectId, title',
      mindMapNodes: 'id, mindMapId, parentId',
      mediaAssets: 'id, projectId, category, entityName',
      storyActs: 'id, projectId, sortOrder',
      heroJourneyStages: 'id, projectId, characterName, stepNumber',
      characterArcPoints: 'id, projectId, characterName, sortOrder',
      sandboxes: 'id, projectId, name, isPromoted',
      sandboxChanges: 'id, sandboxId, entityType',
      projectMembers: 'id, projectId, userEmail, role',
      sharedDocLinks: 'id, manuscriptId, token',
      projectInviteLinks: 'id, projectId, token, isRevoked',
      collaborationAuditLogs: 'id, projectId, userId, timestamp',
      chatChannels: 'id, projectId, isArchived',
      chatMessages: 'id, channelId, createdAt',
      notificationSettings: 'id, userId, emailFrequency',
      teamMeetings: 'id, projectId, date'
    });
    this.version(23).stores({
      metaNodes: 'id, type, status, title',
      metaEdges: 'id, fromId, toId',
      writingGoals: 'id, type, targetWords, deadline',
      writingLogs: 'id, date',
      writingStreak: 'id',
      keyboardShortcuts: 'command',
      manuscripts: 'id, status, title, folderId, category, isArchived',
      manuscriptVersions: 'id, manuscriptId, versionNumber, createdAt',
      pendingSaves: 'id, manuscriptId, timestamp',
      folders: 'id, projectId, parentFolderId',
      comments: 'id, manuscriptId, isResolved, createdAt',
      auditLogs: 'id, type, timestamp',
      reminders: 'id, projectId, alertTime, isRead',
      wikiEntities: 'id, projectId, name, type, isConfidential',
      timelines: 'id, projectId, name',
      timelineEvents: 'id, timelineId, sortOrder',
      geoMaps: 'id, projectId, name',
      geoMapMarkers: 'id, mapId, type',
      mindMaps: 'id, projectId, title',
      mindMapNodes: 'id, mindMapId, parentId',
      mediaAssets: 'id, projectId, category, entityName',
      storyActs: 'id, projectId, sortOrder',
      heroJourneyStages: 'id, projectId, characterName, stepNumber',
      characterArcPoints: 'id, projectId, characterName, sortOrder',
      sandboxes: 'id, projectId, name, isPromoted',
      sandboxChanges: 'id, sandboxId, entityType',
      projectMembers: 'id, projectId, userEmail, role',
      sharedDocLinks: 'id, manuscriptId, token',
      projectInviteLinks: 'id, projectId, token, isRevoked',
      collaborationAuditLogs: 'id, projectId, userId, timestamp',
      chatChannels: 'id, projectId, isArchived',
      chatMessages: 'id, channelId, createdAt',
      notificationSettings: 'id, userId, emailFrequency',
      teamMeetings: 'id, projectId, date',
      voiceMessages: 'id, channelId, createdAt',
      callSessions: 'id, projectId, roomName, status'
    });
    this.version(24).stores({
      metaNodes: 'id, type, status, title',
      metaEdges: 'id, fromId, toId',
      writingGoals: 'id, type, targetWords, deadline',
      writingLogs: 'id, date',
      writingStreak: 'id',
      keyboardShortcuts: 'command',
      manuscripts: 'id, status, title, folderId, category, isArchived',
      manuscriptVersions: 'id, manuscriptId, versionNumber, createdAt',
      pendingSaves: 'id, manuscriptId, timestamp',
      folders: 'id, projectId, parentFolderId',
      comments: 'id, manuscriptId, isResolved, createdAt',
      auditLogs: 'id, type, timestamp',
      reminders: 'id, projectId, alertTime, isRead',
      wikiEntities: 'id, projectId, name, type, isConfidential',
      timelines: 'id, projectId, name',
      timelineEvents: 'id, timelineId, sortOrder',
      geoMaps: 'id, projectId, name',
      geoMapMarkers: 'id, mapId, type',
      mindMaps: 'id, projectId, title',
      mindMapNodes: 'id, mindMapId, parentId',
      mediaAssets: 'id, projectId, category, entityName',
      storyActs: 'id, projectId, sortOrder',
      heroJourneyStages: 'id, projectId, characterName, stepNumber',
      characterArcPoints: 'id, projectId, characterName, sortOrder',
      sandboxes: 'id, projectId, name, isPromoted',
      sandboxChanges: 'id, sandboxId, entityType',
      projectMembers: 'id, projectId, userEmail, role',
      sharedDocLinks: 'id, manuscriptId, token',
      projectInviteLinks: 'id, projectId, token, isRevoked',
      collaborationAuditLogs: 'id, projectId, userId, timestamp',
      chatChannels: 'id, projectId, isArchived',
      chatMessages: 'id, channelId, createdAt',
      notificationSettings: 'id, userId, emailFrequency',
      teamMeetings: 'id, projectId, date',
      voiceMessages: 'id, channelId, createdAt',
      callSessions: 'id, projectId, roomName, status',
      calendarEvents: 'id, projectId, startDate, category',
      memberAvailabilities: 'email, timezone, status'
    });
    this.version(25).stores({
      metaNodes: 'id, type, status, title',
      metaEdges: 'id, fromId, toId',
      writingGoals: 'id, type, targetWords, deadline',
      writingLogs: 'id, date',
      writingStreak: 'id',
      keyboardShortcuts: 'command',
      manuscripts: 'id, status, title, folderId, category, isArchived',
      manuscriptVersions: 'id, manuscriptId, versionNumber, createdAt',
      pendingSaves: 'id, manuscriptId, timestamp',
      folders: 'id, projectId, parentFolderId',
      comments: 'id, manuscriptId, isResolved, createdAt',
      auditLogs: 'id, type, timestamp',
      reminders: 'id, projectId, alertTime, isRead',
      wikiEntities: 'id, projectId, name, type, isConfidential',
      timelines: 'id, projectId, name',
      timelineEvents: 'id, timelineId, sortOrder',
      geoMaps: 'id, projectId, name',
      geoMapMarkers: 'id, mapId, type',
      mindMaps: 'id, projectId, title',
      mindMapNodes: 'id, mindMapId, parentId',
      mediaAssets: 'id, projectId, category, entityName',
      storyActs: 'id, projectId, sortOrder',
      heroJourneyStages: 'id, projectId, characterName, stepNumber',
      characterArcPoints: 'id, projectId, characterName, sortOrder',
      sandboxes: 'id, projectId, name, isPromoted',
      sandboxChanges: 'id, sandboxId, entityType',
      projectMembers: 'id, projectId, userEmail, role',
      sharedDocLinks: 'id, manuscriptId, token',
      projectInviteLinks: 'id, projectId, token, isRevoked',
      collaborationAuditLogs: 'id, projectId, userId, timestamp',
      chatChannels: 'id, projectId, isArchived',
      chatMessages: 'id, channelId, createdAt',
      notificationSettings: 'id, userId, emailFrequency',
      teamMeetings: 'id, projectId, date',
      voiceMessages: 'id, channelId, createdAt',
      callSessions: 'id, projectId, roomName, status',
      calendarEvents: 'id, projectId, startDate, category',
      memberAvailabilities: 'email, timezone, status',
      employees: 'id, projectId, cpf, email',
      payrollRecords: 'id, projectId, monthYear, employeeId'
    });
    this.version(26).stores({
      metaNodes: 'id, type, status, title',
      metaEdges: 'id, fromId, toId',
      writingGoals: 'id, type, targetWords, deadline',
      writingLogs: 'id, date',
      writingStreak: 'id',
      keyboardShortcuts: 'command',
      manuscripts: 'id, status, title, folderId, category, isArchived',
      manuscriptVersions: 'id, manuscriptId, versionNumber, createdAt',
      pendingSaves: 'id, manuscriptId, timestamp',
      folders: 'id, projectId, parentFolderId',
      comments: 'id, manuscriptId, isResolved, createdAt',
      auditLogs: 'id, type, timestamp',
      reminders: 'id, projectId, alertTime, isRead',
      wikiEntities: 'id, projectId, name, type, isConfidential',
      timelines: 'id, projectId, name',
      timelineEvents: 'id, timelineId, sortOrder',
      geoMaps: 'id, projectId, name',
      geoMapMarkers: 'id, mapId, type',
      mindMaps: 'id, projectId, title',
      mindMapNodes: 'id, mindMapId, parentId',
      mediaAssets: 'id, projectId, category, entityName',
      storyActs: 'id, projectId, sortOrder',
      heroJourneyStages: 'id, projectId, characterName, stepNumber',
      characterArcPoints: 'id, projectId, characterName, sortOrder',
      sandboxes: 'id, projectId, name, isPromoted',
      sandboxChanges: 'id, sandboxId, entityType',
      projectMembers: 'id, projectId, userEmail, role',
      sharedDocLinks: 'id, manuscriptId, token',
      projectInviteLinks: 'id, projectId, token, isRevoked',
      collaborationAuditLogs: 'id, projectId, userId, timestamp',
      chatChannels: 'id, projectId, isArchived',
      chatMessages: 'id, channelId, createdAt',
      notificationSettings: 'id, userId, emailFrequency',
      teamMeetings: 'id, projectId, date',
      voiceMessages: 'id, channelId, createdAt',
      callSessions: 'id, projectId, roomName, status',
      calendarEvents: 'id, projectId, startDate, category',
      memberAvailabilities: 'email, timezone, status',
      employees: 'id, projectId, cpf, email',
      payrollRecords: 'id, projectId, monthYear, employeeId',
      vacationRequests: 'id, employeeId, status, type',
      timeClockPunches: 'id, employeeId, punchTime'
    });
    this.version(27).stores({
      metaNodes: 'id, type, status, title',
      metaEdges: 'id, fromId, toId',
      writingGoals: 'id, type, targetWords, deadline',
      writingLogs: 'id, date',
      writingStreak: 'id',
      keyboardShortcuts: 'command',
      manuscripts: 'id, status, title, folderId, category, isArchived',
      manuscriptVersions: 'id, manuscriptId, versionNumber, createdAt',
      pendingSaves: 'id, manuscriptId, timestamp',
      folders: 'id, projectId, parentFolderId',
      comments: 'id, manuscriptId, isResolved, createdAt',
      auditLogs: 'id, type, timestamp',
      reminders: 'id, projectId, alertTime, isRead',
      wikiEntities: 'id, projectId, name, type, isConfidential',
      timelines: 'id, projectId, name',
      timelineEvents: 'id, timelineId, sortOrder',
      geoMaps: 'id, projectId, name',
      geoMapMarkers: 'id, mapId, type',
      mindMaps: 'id, projectId, title',
      mindMapNodes: 'id, mindMapId, parentId',
      mediaAssets: 'id, projectId, category, entityName',
      storyActs: 'id, projectId, sortOrder',
      heroJourneyStages: 'id, projectId, characterName, stepNumber',
      characterArcPoints: 'id, projectId, characterName, sortOrder',
      sandboxes: 'id, projectId, name, isPromoted',
      sandboxChanges: 'id, sandboxId, entityType',
      projectMembers: 'id, projectId, userEmail, role',
      sharedDocLinks: 'id, manuscriptId, token',
      projectInviteLinks: 'id, projectId, token, isRevoked',
      collaborationAuditLogs: 'id, projectId, userId, timestamp',
      chatChannels: 'id, projectId, isArchived',
      chatMessages: 'id, channelId, createdAt',
      notificationSettings: 'id, userId, emailFrequency',
      teamMeetings: 'id, projectId, date',
      voiceMessages: 'id, channelId, createdAt',
      callSessions: 'id, projectId, roomName, status',
      calendarEvents: 'id, projectId, startDate, category',
      memberAvailabilities: 'email, timezone, status',
      employees: 'id, projectId, cpf, email',
      payrollRecords: 'id, projectId, monthYear, employeeId',
      vacationRequests: 'id, employeeId, status, type',
      timeClockPunches: 'id, employeeId, punchTime',
      referenceItems: 'id, projectId, type, title'
    });
    this.version(28).stores({
      metaNodes: 'id, type, status, title',
      metaEdges: 'id, fromId, toId',
      writingGoals: 'id, type, targetWords, deadline',
      writingLogs: 'id, date',
      writingStreak: 'id',
      keyboardShortcuts: 'command',
      manuscripts: 'id, status, title, folderId, category, isArchived',
      manuscriptVersions: 'id, manuscriptId, versionNumber, createdAt',
      pendingSaves: 'id, manuscriptId, timestamp',
      folders: 'id, projectId, parentFolderId',
      comments: 'id, manuscriptId, isResolved, createdAt',
      auditLogs: 'id, type, timestamp',
      reminders: 'id, projectId, alertTime, isRead',
      wikiEntities: 'id, projectId, name, type, isConfidential',
      timelines: 'id, projectId, name',
      timelineEvents: 'id, timelineId, sortOrder',
      geoMaps: 'id, projectId, name',
      geoMapMarkers: 'id, mapId, type',
      mindMaps: 'id, projectId, title',
      mindMapNodes: 'id, mindMapId, parentId',
      mediaAssets: 'id, projectId, category, entityName',
      storyActs: 'id, projectId, sortOrder',
      heroJourneyStages: 'id, projectId, characterName, stepNumber',
      characterArcPoints: 'id, projectId, characterName, sortOrder',
      sandboxes: 'id, projectId, name, isPromoted',
      sandboxChanges: 'id, sandboxId, entityType',
      projectMembers: 'id, projectId, userEmail, role',
      sharedDocLinks: 'id, manuscriptId, token',
      projectInviteLinks: 'id, projectId, token, isRevoked',
      collaborationAuditLogs: 'id, projectId, userId, timestamp',
      chatChannels: 'id, projectId, isArchived',
      chatMessages: 'id, channelId, createdAt',
      notificationSettings: 'id, userId, emailFrequency',
      teamMeetings: 'id, projectId, date',
      voiceMessages: 'id, channelId, createdAt',
      callSessions: 'id, projectId, roomName, status',
      calendarEvents: 'id, projectId, startDate, category',
      memberAvailabilities: 'email, timezone, status',
      employees: 'id, projectId, cpf, email',
      payrollRecords: 'id, projectId, monthYear, employeeId',
      vacationRequests: 'id, employeeId, status, type',
      timeClockPunches: 'id, employeeId, punchTime',
      referenceItems: 'id, projectId, type, title',
      researchNotes: 'id, projectId, title, referenceId'
    });
    this.version(29).stores({
      metaNodes: 'id, type, status, title',
      metaEdges: 'id, fromId, toId',
      writingGoals: 'id, type, targetWords, deadline',
      writingLogs: 'id, date',
      writingStreak: 'id',
      keyboardShortcuts: 'command',
      manuscripts: 'id, status, title, folderId, category, isArchived',
      manuscriptVersions: 'id, manuscriptId, versionNumber, createdAt',
      pendingSaves: 'id, manuscriptId, timestamp',
      folders: 'id, projectId, parentFolderId',
      comments: 'id, manuscriptId, isResolved, createdAt',
      auditLogs: 'id, type, timestamp',
      reminders: 'id, projectId, alertTime, isRead',
      wikiEntities: 'id, projectId, name, type, isConfidential',
      timelines: 'id, projectId, name',
      timelineEvents: 'id, timelineId, sortOrder',
      geoMaps: 'id, projectId, name',
      geoMapMarkers: 'id, mapId, type',
      mindMaps: 'id, projectId, title',
      mindMapNodes: 'id, mindMapId, parentId',
      mediaAssets: 'id, projectId, category, entityName',
      storyActs: 'id, projectId, sortOrder',
      heroJourneyStages: 'id, projectId, characterName, stepNumber',
      characterArcPoints: 'id, projectId, characterName, sortOrder',
      sandboxes: 'id, projectId, name, isPromoted',
      sandboxChanges: 'id, sandboxId, entityType',
      projectMembers: 'id, projectId, userEmail, role',
      sharedDocLinks: 'id, manuscriptId, token',
      projectInviteLinks: 'id, projectId, token, isRevoked',
      collaborationAuditLogs: 'id, projectId, userId, timestamp',
      chatChannels: 'id, projectId, isArchived',
      chatMessages: 'id, channelId, createdAt',
      notificationSettings: 'id, userId, emailFrequency',
      teamMeetings: 'id, projectId, date',
      voiceMessages: 'id, channelId, createdAt',
      callSessions: 'id, projectId, roomName, status',
      calendarEvents: 'id, projectId, startDate, category',
      memberAvailabilities: 'email, timezone, status',
      employees: 'id, projectId, cpf, email',
      payrollRecords: 'id, projectId, monthYear, employeeId',
      vacationRequests: 'id, employeeId, status, type',
      timeClockPunches: 'id, employeeId, punchTime',
      referenceItems: 'id, projectId, type, title',
      researchNotes: 'id, projectId, title, referenceId',
      gameMechanics: 'id, projectId, name, type',
      playableCharacterBalances: 'id, projectId, characterName'
    });
    this.version(30).stores({
      metaNodes: 'id, type, status, title',
      metaEdges: 'id, fromId, toId',
      writingGoals: 'id, type, targetWords, deadline',
      writingLogs: 'id, date',
      writingStreak: 'id',
      keyboardShortcuts: 'command',
      manuscripts: 'id, status, title, folderId, category, isArchived',
      manuscriptVersions: 'id, manuscriptId, versionNumber, createdAt',
      pendingSaves: 'id, manuscriptId, timestamp',
      folders: 'id, projectId, parentFolderId',
      comments: 'id, manuscriptId, isResolved, createdAt',
      auditLogs: 'id, type, timestamp',
      reminders: 'id, projectId, alertTime, isRead',
      wikiEntities: 'id, projectId, name, type, isConfidential',
      timelines: 'id, projectId, name',
      timelineEvents: 'id, timelineId, sortOrder',
      geoMaps: 'id, projectId, name',
      geoMapMarkers: 'id, mapId, type',
      mindMaps: 'id, projectId, title',
      mindMapNodes: 'id, mindMapId, parentId',
      mediaAssets: 'id, projectId, category, entityName',
      storyActs: 'id, projectId, sortOrder',
      heroJourneyStages: 'id, projectId, characterName, stepNumber',
      characterArcPoints: 'id, projectId, characterName, sortOrder',
      sandboxes: 'id, projectId, name, isPromoted',
      sandboxChanges: 'id, sandboxId, entityType',
      projectMembers: 'id, projectId, userEmail, role',
      sharedDocLinks: 'id, manuscriptId, token',
      projectInviteLinks: 'id, projectId, token, isRevoked',
      collaborationAuditLogs: 'id, projectId, userId, timestamp',
      chatChannels: 'id, projectId, isArchived',
      chatMessages: 'id, channelId, createdAt',
      notificationSettings: 'id, userId, emailFrequency',
      teamMeetings: 'id, projectId, date',
      voiceMessages: 'id, channelId, createdAt',
      callSessions: 'id, projectId, roomName, status',
      calendarEvents: 'id, projectId, startDate, category',
      memberAvailabilities: 'email, timezone, status',
      employees: 'id, projectId, cpf, email',
      payrollRecords: 'id, projectId, monthYear, employeeId',
      vacationRequests: 'id, employeeId, status, type',
      timeClockPunches: 'id, employeeId, punchTime',
      referenceItems: 'id, projectId, type, title',
      researchNotes: 'id, projectId, title, referenceId',
      gameMechanics: 'id, projectId, name, type',
      playableCharacterBalances: 'id, projectId, characterName',
      gameRules: 'id, projectId, name, version',
      gameLevels: 'id, projectId, name'
    });
    this.version(31).stores({
      metaNodes: 'id, type, status, title',
      metaEdges: 'id, fromId, toId',
      writingGoals: 'id, type, targetWords, deadline',
      writingLogs: 'id, date',
      writingStreak: 'id',
      keyboardShortcuts: 'command',
      manuscripts: 'id, status, title, folderId, category, isArchived',
      manuscriptVersions: 'id, manuscriptId, versionNumber, createdAt',
      pendingSaves: 'id, manuscriptId, timestamp',
      folders: 'id, projectId, parentFolderId',
      comments: 'id, manuscriptId, isResolved, createdAt',
      auditLogs: 'id, type, timestamp',
      reminders: 'id, projectId, alertTime, isRead',
      wikiEntities: 'id, projectId, name, type, isConfidential',
      timelines: 'id, projectId, name',
      timelineEvents: 'id, timelineId, sortOrder',
      geoMaps: 'id, projectId, name',
      geoMapMarkers: 'id, mapId, type',
      mindMaps: 'id, projectId, title',
      mindMapNodes: 'id, mindMapId, parentId',
      mediaAssets: 'id, projectId, category, entityName',
      storyActs: 'id, projectId, sortOrder',
      heroJourneyStages: 'id, projectId, characterName, stepNumber',
      characterArcPoints: 'id, projectId, characterName, sortOrder',
      sandboxes: 'id, projectId, name, isPromoted',
      sandboxChanges: 'id, sandboxId, entityType',
      projectMembers: 'id, projectId, userEmail, role',
      sharedDocLinks: 'id, manuscriptId, token',
      projectInviteLinks: 'id, projectId, token, isRevoked',
      collaborationAuditLogs: 'id, projectId, userId, timestamp',
      chatChannels: 'id, projectId, isArchived',
      chatMessages: 'id, channelId, createdAt',
      notificationSettings: 'id, userId, emailFrequency',
      teamMeetings: 'id, projectId, date',
      voiceMessages: 'id, channelId, createdAt',
      callSessions: 'id, projectId, roomName, status',
      calendarEvents: 'id, projectId, startDate, category',
      memberAvailabilities: 'email, timezone, status',
      employees: 'id, projectId, cpf, email',
      payrollRecords: 'id, projectId, monthYear, employeeId',
      vacationRequests: 'id, employeeId, status, type',
      timeClockPunches: 'id, employeeId, punchTime',
      referenceItems: 'id, projectId, type, title',
      researchNotes: 'id, projectId, title, referenceId',
      gameMechanics: 'id, projectId, name, type',
      playableCharacterBalances: 'id, projectId, characterName',
      gameRules: 'id, projectId, name, version',
      gameLevels: 'id, projectId, name',
      gameShops: 'id, projectId, shopName'
    });
    this.version(32).stores({
      metaNodes: 'id, type, status, title',
      metaEdges: 'id, fromId, toId',
      writingGoals: 'id, type, targetWords, deadline',
      writingLogs: 'id, date',
      writingStreak: 'id',
      keyboardShortcuts: 'command',
      manuscripts: 'id, status, title, folderId, category, isArchived',
      manuscriptVersions: 'id, manuscriptId, versionNumber, createdAt',
      pendingSaves: 'id, manuscriptId, timestamp',
      folders: 'id, projectId, parentFolderId',
      comments: 'id, manuscriptId, isResolved, createdAt',
      auditLogs: 'id, type, timestamp',
      reminders: 'id, projectId, alertTime, isRead',
      wikiEntities: 'id, projectId, name, type, isConfidential',
      timelines: 'id, projectId, name',
      timelineEvents: 'id, timelineId, sortOrder',
      geoMaps: 'id, projectId, name',
      geoMapMarkers: 'id, mapId, type',
      mindMaps: 'id, projectId, title',
      mindMapNodes: 'id, mindMapId, parentId',
      mediaAssets: 'id, projectId, category, entityName',
      storyActs: 'id, projectId, sortOrder',
      heroJourneyStages: 'id, projectId, characterName, stepNumber',
      characterArcPoints: 'id, projectId, characterName, sortOrder',
      sandboxes: 'id, projectId, name, isPromoted',
      sandboxChanges: 'id, sandboxId, entityType',
      projectMembers: 'id, projectId, userEmail, role',
      sharedDocLinks: 'id, manuscriptId, token',
      projectInviteLinks: 'id, projectId, token, isRevoked',
      collaborationAuditLogs: 'id, projectId, userId, timestamp',
      chatChannels: 'id, projectId, isArchived',
      chatMessages: 'id, channelId, createdAt',
      notificationSettings: 'id, userId, emailFrequency',
      teamMeetings: 'id, projectId, date',
      voiceMessages: 'id, channelId, createdAt',
      callSessions: 'id, projectId, roomName, status',
      calendarEvents: 'id, projectId, startDate, category',
      memberAvailabilities: 'email, timezone, status',
      employees: 'id, projectId, cpf, email',
      payrollRecords: 'id, projectId, monthYear, employeeId',
      vacationRequests: 'id, employeeId, status, type',
      timeClockPunches: 'id, employeeId, punchTime',
      referenceItems: 'id, projectId, type, title',
      researchNotes: 'id, projectId, title, referenceId',
      gameMechanics: 'id, projectId, name, type',
      playableCharacterBalances: 'id, projectId, characterName',
      gameRules: 'id, projectId, name, version',
      gameLevels: 'id, projectId, name',
      gameShops: 'id, projectId, shopName',
      objectiveOkrs: 'id, projectId, title, ownerTeamOrProject, status',
      okrCheckInLogs: 'id, objectiveId, keyResultId, authorEmail',
      okrTaskLinks: 'id, taskId, objectiveId, keyResultId'
    });
    this.version(33).stores({
      metaNodes: 'id, type, status, title',
      metaEdges: 'id, fromId, toId',
      writingGoals: 'id, type, targetWords, deadline',
      writingLogs: 'id, date',
      writingStreak: 'id',
      keyboardShortcuts: 'command',
      manuscripts: 'id, status, title, folderId, category, isArchived',
      manuscriptVersions: 'id, manuscriptId, versionNumber, createdAt',
      pendingSaves: 'id, manuscriptId, timestamp',
      folders: 'id, projectId, parentFolderId',
      comments: 'id, manuscriptId, isResolved, createdAt',
      auditLogs: 'id, type, timestamp',
      reminders: 'id, projectId, alertTime, isRead',
      wikiEntities: 'id, projectId, name, type, isConfidential',
      timelines: 'id, projectId, name',
      timelineEvents: 'id, timelineId, sortOrder',
      geoMaps: 'id, projectId, name',
      geoMapMarkers: 'id, mapId, type',
      mindMaps: 'id, projectId, title',
      mindMapNodes: 'id, mindMapId, parentId',
      mediaAssets: 'id, projectId, category, entityName',
      storyActs: 'id, projectId, sortOrder',
      heroJourneyStages: 'id, projectId, characterName, stepNumber',
      characterArcPoints: 'id, projectId, characterName, sortOrder',
      sandboxes: 'id, projectId, name, isPromoted',
      sandboxChanges: 'id, sandboxId, entityType',
      projectMembers: 'id, projectId, userEmail, role',
      sharedDocLinks: 'id, manuscriptId, token',
      projectInviteLinks: 'id, projectId, token, isRevoked',
      collaborationAuditLogs: 'id, projectId, userId, timestamp',
      chatChannels: 'id, projectId, isArchived',
      chatMessages: 'id, channelId, createdAt',
      notificationSettings: 'id, userId, emailFrequency',
      teamMeetings: 'id, projectId, date',
      voiceMessages: 'id, channelId, createdAt',
      callSessions: 'id, projectId, roomName, status',
      calendarEvents: 'id, projectId, startDate, category',
      memberAvailabilities: 'email, timezone, status',
      employees: 'id, projectId, cpf, email',
      payrollRecords: 'id, projectId, monthYear, employeeId',
      vacationRequests: 'id, employeeId, status, type',
      timeClockPunches: 'id, employeeId, punchTime',
      referenceItems: 'id, projectId, type, title',
      researchNotes: 'id, projectId, title, referenceId',
      gameMechanics: 'id, projectId, name, type',
      playableCharacterBalances: 'id, projectId, characterName',
      gameRules: 'id, projectId, name, version',
      gameLevels: 'id, projectId, name',
      gameShops: 'id, projectId, shopName',
      objectiveOkrs: 'id, projectId, title, ownerTeamOrProject, status',
      okrCheckInLogs: 'id, objectiveId, keyResultId, authorEmail',
      okrTaskLinks: 'id, taskId, objectiveId, keyResultId',
      corporatePortfolios: 'id, globalBudget',
      resourceAllocations: 'id, employeeId, projectId, resourceType',
      projectCostLogs: 'id, projectId, category',
      projectFinancials: 'projectId, isInternal'
    });
  }
}

export const db = new EldritchDatabase();

export async function deleteNodeTransaction(nodeId: string) {
  await db.transaction('rw', db.metaNodes, db.metaEdges, async () => {
    // Delete the node
    await db.metaNodes.delete(nodeId);
    
    // Find all edges where fromId === nodeId or toId === nodeId
    const edgesToDelete = await db.metaEdges
      .filter(edge => edge.fromId === nodeId || edge.toId === nodeId)
      .toArray();
      
    // Delete those edges
    await Promise.all(edgesToDelete.map(edge => db.metaEdges.delete(edge.id)));
  });
}
