'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { ChatChannel, ChatMessage } from '@eldritch/domain';
import { db } from '../../db/schema';
import { useApp } from '../../context/AppContext';
import './chat.css';

export default function ChatPage() {
  const { activeProject, user } = useApp(); const [channels,setChannels]=useState<ChatChannel[]>([]);const [messages,setMessages]=useState<ChatMessage[]>([]);const [activeId,setActiveId]=useState('');const [newChannel,setNewChannel]=useState('');const [text,setText]=useState('');const [creating,setCreating]=useState(false);
  const active=useMemo(()=>channels.find(channel=>channel.id===activeId)??null,[channels,activeId]);
  const load=async()=>{if(!activeProject)return;const records=await db.chatChannels.where('projectId').equals(activeProject.id).toArray();setChannels(records.filter(channel=>!channel.isArchived).sort((a,b)=>a.createdAt.localeCompare(b.createdAt)));setActiveId(current=>records.some(channel=>channel.id===current)?current:records[0]?.id??'');};
  const loadMessages=async()=>{if(!activeId){setMessages([]);return;}setMessages((await db.chatMessages.where('channelId').equals(activeId).toArray()).sort((a,b)=>a.createdAt.localeCompare(b.createdAt)));};
  useEffect(()=>{void load();},[activeProject?.id]);useEffect(()=>{void loadMessages();},[activeId]);
  const create=async(event:FormEvent)=>{event.preventDefault();if(!activeProject||!newChannel.trim())return;const channel:ChatChannel={id:crypto.randomUUID(),projectId:activeProject.id,name:newChannel.trim(),isArchived:false,createdAt:new Date().toISOString()};await db.chatChannels.put(channel);setNewChannel('');setCreating(false);await load();setActiveId(channel.id);};
  const send=async(event:FormEvent)=>{event.preventDefault();if(!active||!text.trim())return;await db.chatMessages.put({id:crypto.randomUUID(),channelId:active.id,senderEmail:user?.email??'local@autor',senderName:user?.name??'Autor',content:text.trim(),createdAt:new Date().toISOString()});setText('');await loadMessages();};
  return <main className="page chat-page"><header className="page-heading"><div><p className="eyebrow">Colaboração</p><h1>Conversas do projeto</h1><p>Registre decisões e cite capítulos com <code>[[Título do capítulo]]</code>.</p></div><button className="primary-button" onClick={()=>setCreating(true)}>Novo canal</button></header>{creating&&<form className="surface-card channel-form" onSubmit={create}><input autoFocus value={newChannel} onChange={event=>setNewChannel(event.target.value)} placeholder="Ex.: Revisão do capítulo 4"/><button className="primary-button">Criar canal</button><button type="button" className="secondary-button" onClick={()=>setCreating(false)}>Cancelar</button></form>}<section className="chat-layout"><aside className="surface-card channel-list"><h2>Canais</h2>{channels.map(channel=><button key={channel.id} className={channel.id===activeId?'is-active':''} onClick={()=>setActiveId(channel.id)}>{channel.name}</button>)}{!channels.length&&<p className="muted">Crie um canal para iniciar uma conversa.</p>}</aside><section className="surface-card conversation">{!active?<div className="empty-state"><h2>Escolha ou crie um canal.</h2><p>As conversas permanecem no armazenamento local deste projeto.</p></div>:<><header><div><h2>{active.name}</h2><p>{messages.length} mensagens locais</p></div></header><div className="message-list">{messages.map(message=><article key={message.id}><div><strong>{message.senderName}</strong><time>{new Date(message.createdAt).toLocaleString('pt-BR')}</time></div><p>{message.content}</p></article>)}{!messages.length&&<p className="muted">Ainda não há mensagens.</p>}</div><form onSubmit={send}><textarea value={text} onChange={event=>setText(event.target.value)} placeholder="Escreva uma decisão, uma pergunta ou uma referência ao manuscrito." rows={3}/><button className="primary-button">Enviar</button></form></>}</section></section></main>;
}
